import Head from "next/head";
import styled from "styled-components";
import { NextPage } from "next";
import { SidebarNavigation } from "../components/SidebarNavigation";

type ContainerProps = {
  theme: string;
};

const Container = styled.div<ContainerProps>`
  padding: 0 2rem;
  height: 100vh;
  ${(props) => props.theme === "dark" && "background:black"}
`;

const Main = styled.main`
  min-height: 100vh;
  padding: 4rem o;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const Title = styled.h1`
  margin: 0;
  line-height: 1.15;
  font-size: 4rem;
  text-align: center;

  a {
    color: #0070f3;
    text-decoration: none;
  }

  a:hover,
  a:focus,
  a:active {
    text-decoration: underline;
  }
`;

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <SidebarNavigation />
        <Title>Get started by editing</Title>
        <p>Get started by editing</p>
      </Main>
    </Container>
  );
};

export default Home;
