import Head from "next/head";
import styled from "styled-components";

type ContainerProps = {
  theme: string;
};
const Container = styled.div<ContainerProps>`
  padding: 0 2rem;
  height: 100vh;
  background: blue;
  ${(props) => props.theme === "dark" && "background:black"}
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container theme="light">Hello</Container>
      </main>
    </>
  );
}
