import Head from "next/head";
import { NextPage } from "next";
import { SidebarNavigation } from "../components/SidebarNavigation";

const Issues: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SidebarNavigation />
        {/* <Title>Get started by editing</Title> */}
        <p>Get started by editing</p>
      </main>
    </div>
  );
};

export default Issues;
